# Generated by Django 5.0.1 on 2024-01-05 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('score', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
            ],
        ),
    ]
